### ISSUE TITLE
大神救救我

### ISSUE THREAD

**Issue by fengtaoliming** [xen0n/my-portage-conf#1]
上次你给的stage3我已经按照手册安装差不多了，用的fedora28光盘chroot,内核用的官方5.5内核，编译完成了,但是不知道怎么引导。
处理器是3a3000，固件是昆仑固件，应该怎么引导系统，我看了下fedora28的系统，它的boot目录好复杂，尤其是grub.efi，直接看懵比了，怎么才能把系统跑起来？我看你的use里面有grub，是用的gentoo官方的么？
另外，我还想问下，你维护的内核可以跑在3a3000么？如果可以，那内核编译需要注意哪些？需不需要加一些特殊的参数。

**Comment by xen0n** [comment]
回家给你看一下= =引导确实是个问题，因为支持目前龙芯 UEFI 实现的 grub 补丁还没 upstream。上游的 grub 暂时不能用。

我的内核指的是 xen0n/linux 那个？3A3000 可用的，想偷懒的话直接以 fedora28 的 .config 为基础就好。应该没啥特殊参数。

**Comment by xen0n** [comment]
3A4000 目前我的内核 fork 不可用，因为上游没有 7A 支持。这部分工作 @flygoat 在推进了。

**Comment by xen0n** [comment]
我的 `/boot/efi` 目录结构：

```
/boot/efi
└── EFI
    └── BOOT
        ├── BOOTMIPS.EFI
        └── grub.cfg
```

`BOOTMIPS.EFI` 是 copy 的 fc28 的

`grub.cfg` 也是借鉴的 fc28 自带的:

```
set default=0
set timeout=5
set menu_color_normal=white/black
set menu_color_highlight=yellow/black

menuentry 'Gentoo 5.4.21' {
set root=(hd0,gpt2)
linux /vmlinuz-5.4.21-xen0n+ root=/dev/mapper/vgsys-rootvol ro rootflags=subvol=gentoo-3a4000 swiotlb=16384 console=ttyS0,115200 ieee754=relaxed
initrd /initramfs-5.4.21-xen0n+.img
boot
}
```

initramfs 是 dracut 做的，我的 `/` 分区是放在 btrfs 的一个 subvolume 所以有 `rootflags`，我接了串口调试所以有 `console`。`swiotlb` 不知道是不是必须的，`ieee754=relaxed` 是必须的！

你可能自己把 `set root` 的部分根据自己的分区表调整一下就好了，我的分区表供参考：

```
Device              Start        End    Sectors  Size Type
/dev/nvme0n1p1       2048     526335     524288  256M EFI System
/dev/nvme0n1p2     526336    1050623     524288  256M Linux filesystem
/dev/nvme0n1p3    1050624 1886416270 1885365647  899G Linux LVM
/dev/nvme0n1p4 1886416896 1953525134   67108239   32G Linux swap
```

**Comment by xen0n** [comment]
啊，不好意思才看到你是 3A3000。。他的昆仑固件跟 3A4000 的应该不太一样，你是龙梦的 3A3000+7A 板子么？

**Comment by fengtaoliming** [comment]
首先表示感谢，目前是这样，启动问题解决了，我的做法跟你差不多，拷贝了原机中标麒麟系统里面的grub.efi,内核是fedora28 kde live5光盘里面的，跑起来没问题。但是用fedora28的.config编译gentoo-source5.6.3编译没出错，跑不起不来。
至于板子，我的机子曙光L300-G25整机，拆壳子太麻烦，只拆过一次，加了一块机械硬盘，我猜是龙梦的板子。
这网真是那啥了，每次clone到一半就断。直到现在我也没下载下来。

**Comment by fengtaoliming** [comment]
有没有可能下载到fedora28的内核源码？

**Comment by fengtaoliming** [comment]
刚注意到，大神你都3a4000了，真豪横！

**Comment by fengtaoliming** [comment]
我下载fc28-5.4的分支代码，在我的机器上可以起来，loongson-xen0n-5.5.x分支起不来。这俩分支差在哪儿？

**Comment by xen0n** [comment]
不清楚，估计是 config 选项区别吧。。我也好久没折腾 3a3000 内核了= = 这几天应该也没空

**Comment by xen0n** [comment]
Closed due to inactivity.
